'use server';

/**
 * Local file upload for the editor's Image tool — goes to Supabase Storage
 * (bucket `post-images`, public, 10MB limit, image mime types only). Uses the
 * Storage REST API directly via `fetch` with the service-role key — no
 * `@supabase/supabase-js` client, consistent with the rest of this app (raw
 * `pg` for the database, raw REST for Gemini, raw REST here).
 *
 * Auth: this is a Server Action, so it only runs for a request that already
 * passed middleware's session check for /admin/*. It does not itself verify
 * a capability — image upload is treated as part of "can edit a post," which
 * every path that reaches this form already required.
 */

const BUCKET = 'post-images';
const MAX_BYTES = 10 * 1024 * 1024;
const ALLOWED_TYPES = new Set(['image/png', 'image/jpeg', 'image/webp', 'image/gif', 'image/svg+xml']);

function supabaseUrl(): string {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  if (!url) throw new Error('NEXT_PUBLIC_SUPABASE_URL is not configured.');
  return url;
}

function serviceRoleKey(): string {
  const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!key) throw new Error('SUPABASE_SERVICE_ROLE_KEY is not configured.');
  return key;
}

function safeFileName(ext: string): string {
  const cleanExt = ext.toLowerCase().replace(/[^a-z0-9]/g, '') || 'bin';
  return `${crypto.randomUUID()}.${cleanExt}`;
}

/**
 * Shared upload primitive — bytes in, public URL out. Used by both
 * `uploadPostImage` (a user's local file) and `generateAndSaveImage`
 * (`ai-actions.ts`, AI-generated bytes from Gemini) so there is exactly one
 * place that talks to Supabase Storage. Public by design (bucket is public):
 * this is how "accessible from any machine, or anywhere" is satisfied for
 * free, with no separate access mechanism to build.
 */
export async function uploadBytesToStorage(
  bytes: Uint8Array,
  mimeType: string,
  extension: string,
): Promise<{ ok: true; url: string } | { ok: false; error: string }> {
  if (bytes.byteLength === 0) return { ok: false, error: 'No image data.' };
  if (bytes.byteLength > MAX_BYTES) {
    return { ok: false, error: `Image is ${(bytes.byteLength / 1024 / 1024).toFixed(1)}MB — the limit is 10MB.` };
  }
  if (!ALLOWED_TYPES.has(mimeType)) {
    return { ok: false, error: `Type "${mimeType || 'unknown'}" is not allowed. Use PNG, JPEG, WebP, GIF, or SVG.` };
  }

  const path = safeFileName(extension);

  try {
    const response = await fetch(`${supabaseUrl()}/storage/v1/object/${BUCKET}/${path}`, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${serviceRoleKey()}`,
        'Content-Type': mimeType,
        'x-upsert': 'false',
      },
      // TS's DOM lib types BodyInit as wanting Uint8Array<ArrayBuffer> specifically;
      // `bytes` here is typed Uint8Array<ArrayBufferLike> (it may come from
      // Buffer.from() upstream) — a real type-checking granularity mismatch, not
      // a runtime one (Node's fetch accepts any Uint8Array body correctly).
      body: bytes as BodyInit,
    });

    if (!response.ok) {
      const body = await response.text().catch(() => '');
      return { ok: false, error: `Upload failed (${response.status}): ${body.slice(0, 200)}` };
    }

    return { ok: true, url: `${supabaseUrl()}/storage/v1/object/public/${BUCKET}/${path}` };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : 'Upload failed.' };
  }
}

export async function uploadPostImage(
  formData: FormData,
): Promise<{ ok: true; url: string } | { ok: false; error: string }> {
  const file = formData.get('file');
  if (!(file instanceof File)) return { ok: false, error: 'No file provided.' };

  const bytes = new Uint8Array(await file.arrayBuffer());
  const ext = file.name.split('.').pop() || 'bin';
  return uploadBytesToStorage(bytes, file.type, ext);
}
