// Placeholder legal text for a template — have it reviewed for your business and jurisdiction.
import type { Metadata } from 'next';
import { pageMetadata } from '@/lib/page-seo';
import { siteConfig } from '@/config/site';
import { getCompany, formatAddress } from '@/lib/company';

// Legal text. Changes about once a year.
export const revalidate = 86400;

// Title and description come from site_content['page_seo'] when set, so SEO
// copy can be tuned against Search Console data without a deploy. The values
// below are the fallback, and the database only ever overrides them.
export async function generateMetadata(): Promise<Metadata> {
  return pageMetadata('/terms', {
    title: 'Terms of Service',
    description:
      'The terms governing use of Your Company Private Limited\'s website and services.',
  });
}


export default async function TermsOfServicePage() {
  const company = await getCompany();
  return (
    <main className="mx-auto max-w-3xl px-6 py-20 prose prose-slate dark:prose-invert">
      <h1>Terms of Service</h1>
      <p>Last updated: 11 August 2026</p>

      <p>
        These Terms of Service (&quot;Terms&quot;) govern your use of {siteConfig.url} and related
        communication channels operated by {company.legal_name} (&quot;YourSite&quot;,
        &quot;we&quot;, &quot;us&quot;), Your City, India, including our WhatsApp Business number and
        website contact forms. By using our website or messaging our WhatsApp number, you agree to these
        Terms.
      </p>

      <h2>1. Our services</h2>
      <p>
        YourSite provides the services described on this website, along with published
        templates and educational content. Descriptions of services on this website are
        informational and do not constitute a binding offer until confirmed separately in writing (e.g. a
        signed proposal or invoice).
      </p>

      <h2>2. Automated assistance</h2>
      <p>
        Messages sent to our WhatsApp Business number may be answered by an AI assistant. Automated
        replies are clearly generated by an assistant, not a person, and any message we assess as needing
        human judgment — including complaints, refund requests, or payment issues — is automatically
        routed to a person on our team. You may ask to speak with a person at any time.
      </p>

      <h2>3. Templates and digital products</h2>
      <p>
        Where we offer templates or digital products for purchase, access is granted for your own use
        upon payment confirmation. Unless stated otherwise at the point of sale, digital products are
        non-refundable once access has been granted, given their nature as immediately deliverable digital
        goods.
      </p>

      <h2>4. Acceptable use</h2>
      <p>
        You agree not to use our website or communication channels to transmit unlawful, abusive, or
        fraudulent content, or to attempt to disrupt, reverse-engineer, or gain unauthorized access to our
        systems.
      </p>

      <h2>5. Intellectual property</h2>
      <p>
        Content on this website — including text, graphics, logos, and published templates — is owned by
        YourSite or its licensors and may not be reproduced or redistributed without permission, except
        where a template is explicitly offered under a separate open license.
      </p>

      <h2>6. Limitation of liability</h2>
      <p>
        Our website and automated assistant are provided on an &quot;as is&quot; basis. To the fullest
        extent permitted by law, YourSite is not liable for indirect or consequential loss arising from
        your use of the website or communication channels; nothing in these Terms limits liability that
        cannot lawfully be excluded.
      </p>

      <h2>7. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time; the &quot;Last updated&quot; date above reflects the
        most recent revision. Continued use of our website or communication channels after a change
        constitutes acceptance of the updated Terms.
      </p>

      <h2>8. Governing law</h2>
      <p>These Terms are governed by the laws of India, with courts in Your City having jurisdiction.</p>

      <h2>9. Contact</h2>
      <p>
        {company.legal_name}, {formatAddress(company)}
        <br />
        {[company.gstin && `GSTIN ${company.gstin}`, company.cin && `CIN ${company.cin}`].filter(Boolean).join(' · ')}
        {(company.gstin || company.cin) && <br />}
        Email: <a href={`mailto:${siteConfig.links.contact.email}`}>{siteConfig.links.contact.email}</a>
      </p>
    </main>
  );
}
