// Placeholder legal text for a template — have it reviewed for your business and jurisdiction.
import type { Metadata } from 'next';
import { pageMetadata } from '@/lib/page-seo';
import { siteConfig } from '@/config/site';
import { getCompany, formatAddress } from '@/lib/company';

// Legal text. Changes about once a year.
export const revalidate = 86400;

// Title and description come from site_content['page_seo'] when set, so SEO
// copy can be tuned against Search Console data without a deploy. The values
// below are the fallback, and the database only ever overrides them.
export async function generateMetadata(): Promise<Metadata> {
  return pageMetadata('/privacy', {
    title: 'Privacy Policy',
    description:
      'How Your Company Private Limited collects, uses, and protects your data.',
  });
}


export default async function PrivacyPolicyPage() {
  const company = await getCompany();
  return (
    <main className="mx-auto max-w-3xl px-6 py-20 prose prose-slate dark:prose-invert">
      <h1>Privacy Policy</h1>
      <p>Last updated: 9 September 2026</p>

      <p>
        {company.legal_name} (&quot;YourSite&quot;, &quot;we&quot;, &quot;us&quot;),
        Your City, India, operates {siteConfig.url} and related communication channels, including our
        WhatsApp Business number, website contact forms, and account/checkout system. This policy explains
        what data we collect, why, and how you can control it. This policy is written in line with
        India&apos;s Digital Personal Data Protection Act, 2023 (&quot;DPDP Act&quot;).
      </p>

      <h2>1. What we collect</h2>
      <ul>
        <li>Contact form submissions: name, email, phone number, and message content.</li>
        <li>
          WhatsApp conversations: your phone number and message content, when you message our WhatsApp
          Business number. Messages may be processed by an AI assistant to generate a reply; a human
          reviews and responds to any conversation the assistant escalates.
        </li>
        <li>
          Account data: if you create a YourSite account (via Google sign-in or email + password), we
          store your name, email address, and — once you verify it — your WhatsApp number. Verification
          happens by you sending us a message on WhatsApp; we reply with a one-time numeric code, and we
          keep a record of the consent shown to you and when you gave it.
        </li>
        <li>Order history: products/services you purchase and payment status (not full card/payment
          details — those are handled directly by our payment processor).</li>
        <li>Basic website analytics (pages visited, general location by IP) to understand site usage.</li>
      </ul>

      <h2>2. Why we collect it, and on what basis</h2>
      <ul>
        <li>
          <strong>Providing the service you asked for</strong> — creating your account, fulfilling and
          tracking an order, verifying your WhatsApp number so we can reach you about it, responding to an
          inquiry. This data is voluntarily given by you for a purpose you initiated, so we rely on this
          directly rather than asking for a separate consent checkbox for it — consistent with the DPDP
          Act&apos;s treatment of data voluntarily provided for a specified purpose.
        </li>
        <li>
          <strong>Marketing / update messages on WhatsApp</strong> — a distinct purpose from the above, and
          only if you separately, explicitly opt in via an un-pre-checked checkbox at signup. You can
          withdraw this at any time by replying <strong>STOP</strong> to us on WhatsApp — see
          &quot;Your rights&quot; below.
        </li>
        <li>To improve our WhatsApp assistant and website based on real usage.</li>
        <li>We do not sell your data. We do not share it with third parties except service providers
          (e.g. Meta, for WhatsApp delivery; our hosting, database, and payment providers) strictly to
          operate the service.</li>
      </ul>

      <h2>3. WhatsApp Business Platform</h2>
      <p>
        Our WhatsApp number is operated via Meta&apos;s WhatsApp Business Platform. Meta processes
        message content to deliver it between you and us, per{' '}
        <a href="https://www.whatsapp.com/legal/business-policy" target="_blank" rel="noopener noreferrer">
          Meta&apos;s WhatsApp Business Messaging Policy
        </a>. Automated replies are clearly generated by an assistant; you can always ask to speak to a
        person, and any message mentioning a complaint, refund, or payment is automatically routed to a
        human. WhatsApp number verification (the one-time code we send after you message us) is handled
        the same way — as an ordinary text reply, never a link.
      </p>
      <p>
        <strong>Opting out.</strong> If you have given us your WhatsApp number, you can stop all messages
        from us at any time by replying <strong>STOP</strong> to our WhatsApp number. We record the
        opt-out immediately and send nothing further, other than a single confirmation that it took
        effect. <strong>START</strong> opts you back in. This works whether or not you hold an account
        with us, and needs no email, form, or request to support. Opting out of messages does not delete
        the data we already hold — to ask for that, see &quot;Your rights&quot; below.
      </p>

      <h2>4. Where your data is stored</h2>
      <p>
        Our servers and database are hosted in India. This is a choice we&apos;ve made for
        performance and control, not a requirement of the DPDP Act — the Act does not currently mandate
        that Indian companies store personal data only within India.
      </p>

      <h2>5. Data retention</h2>
      <p>
        We retain conversation, contact-form, account, and order records only as long as needed to provide
        the service, maintain an audit trail (including of verification consent), or meet legal/tax
        obligations, and delete or anonymize them on request as described below.
      </p>

      <h2>6. Your rights</h2>
      <p>
        You may request access to, correction of, or deletion of your data at any time by emailing{' '}
        <a href={`mailto:${siteConfig.links.contact.email}`}>{siteConfig.links.contact.email}</a> — see our{' '}
        <a href="/data-deletion">Data Deletion</a> page for details. If you opted in to WhatsApp marketing
        updates, you can withdraw that consent at any time from your account settings or by telling us on
        WhatsApp. We aim to resolve any request within 90 days; if you&apos;re not satisfied with how we&apos;ve
        handled it, you may complain to the Data Protection Board of India.
      </p>

      <h2>7. If something goes wrong</h2>
      <p>
        In the event of a personal data breach, we will notify affected individuals without undue delay
        and report it to the Data Protection Board of India within the required timeframe.
      </p>

      <h2>8. Contact</h2>
      <p>
        {company.legal_name}, {formatAddress(company)}
        <br />
        {[company.gstin && `GSTIN ${company.gstin}`, company.cin && `CIN ${company.cin}`].filter(Boolean).join(' · ')}
        {(company.gstin || company.cin) && <br />}
        Email: <a href={`mailto:${siteConfig.links.contact.email}`}>{siteConfig.links.contact.email}</a>
      </p>
    </main>
  );
}
