#!/usr/bin/env node
/**
 * gen-e2e.mjs — generate the test cases that can be derived, so humans only
 * write the ones that cannot.
 *
 * The problem: the backend schema is fixed by the template, but the FEATURES
 * on top of it vary per adopter. A hand-written list of routes and roles is
 * wrong the moment someone adds a page. A suite that only covers what its
 * author remembered is a suite whose coverage silently decays.
 *
 * So: derive from the two things that are already true.
 *
 *   ROUTES  come from the filesystem. Next.js App Router already encodes every
 *           page as a path, so `src/app/**\/page.tsx` IS the route manifest —
 *           no second list to keep in sync, and a new page is covered the
 *           moment it exists.
 *
 *   ROLES   come from role_capabilities in the database. That table is the
 *           permission model; generating from it means a new role or resource
 *           gets a test without anyone remembering to add one.
 *
 * What this does NOT generate: anything requiring judgement about what a page
 * MEANS. A generator can assert /pricing renders, has one h1 and no console
 * errors. It cannot know the annual toggle should cut the monthly figure by
 * 20%. That is what the agentic pass and hand-written specs are for — and the
 * division is deliberate, because a generator that guesses intent produces
 * confident nonsense.
 *
 * Usage:
 *   node scripts/gen-e2e.mjs            # write e2e/generated/
 *   node scripts/gen-e2e.mjs --list     # print what it would generate
 */

import { readdirSync, statSync, writeFileSync, mkdirSync, existsSync, rmSync } from 'node:fs';
import { join, relative } from 'node:path';

const APP_DIR = 'src/app';
const OUT_DIR = 'e2e/generated';

/* ── Routes, from the filesystem ────────────────────────────────────────── */

/**
 * Next.js route groups — (marketing), (app) — organise files without appearing
 * in the URL. Dynamic segments ([id]) need a real value we do not have, and
 * private folders (_components) are not routes at all.
 */
function toRoute(fsPath) {
  const rel = relative(APP_DIR, fsPath).replace(/\/page\.tsx?$/, '');
  const segments = rel
    .split('/')
    .filter((s) => s && !(s.startsWith('(') && s.endsWith(')')) && !s.startsWith('_'));
  if (segments.some((s) => s.startsWith('[') || s === 'api')) return null;
  return '/' + segments.join('/');
}

function walk(dir, hits = []) {
  for (const entry of readdirSync(dir)) {
    const p = join(dir, entry);
    const st = statSync(p);
    if (st.isDirectory()) walk(p, hits);
    else if (/^page\.tsx?$/.test(entry)) hits.push(p);
  }
  return hits;
}

function discoverRoutes() {
  if (!existsSync(APP_DIR)) return [];
  const routes = walk(APP_DIR)
    .map(toRoute)
    .filter(Boolean)
    // An admin route behind auth cannot be smoke-tested as a visitor, and a
    // 307 to /login is the correct answer there rather than a failure.
    .filter((r) => !r.startsWith('/admin'));
  return [...new Set(routes)].sort();
}

/* ── Emit ───────────────────────────────────────────────────────────────── */

const HEADER = `/**
 * GENERATED by scripts/gen-e2e.mjs — do not edit.
 *
 * Regenerate with \`pnpm gen:e2e\`. Add hand-written cases in e2e/*.spec.ts
 * instead; anything here is derived from the filesystem and will be
 * overwritten.
 *
 * These are smoke assertions: the page renders, says one thing it is, and does
 * not error. They deliberately assert nothing about MEANING — a generator that
 * guesses what a page is for produces confident nonsense. Meaning is covered
 * by the agentic pass and by the hand-written specs.
 */
`;

function routeSpec(routes) {
  return `${HEADER}
import { test, expect } from '@playwright/test';

const ROUTES = ${JSON.stringify(routes, null, 2)};

for (const route of ROUTES) {
  test.describe(\`route \${route}\`, () => {
    test('renders without a server error', async ({ page }) => {
      const res = await page.goto(route);
      const status = res?.status() ?? 0;
      // A redirect is a legitimate answer; a 5xx never is.
      expect(status, \`\${route} returned \${status}\`).toBeLessThan(500);
    });

    test('has exactly one h1', async ({ page }) => {
      await page.goto(route);
      await page.waitForLoadState('networkidle');
      const count = await page.locator('h1').count();
      // Zero h1s leaves a screen-reader user with no page title; several make
      // the document outline meaningless.
      expect(count, \`\${route} has \${count} h1 elements\`).toBe(1);
    });

    test('logs no console errors', async ({ page }) => {
      // Annotated: these files are type-checked by \`pnpm typecheck\`, and an
      // untyped [] is an implicit any[] under noImplicitAny.
      const errors: string[] = [];
      page.on('console', (m) => { if (m.type() === 'error') errors.push(m.text()); });
      page.on('pageerror', (e) => errors.push(e.message));

      await page.goto(route);
      await page.waitForLoadState('networkidle');

      // Third-party noise (blocked trackers, extension chatter) is not ours.
      const ours = errors.filter((e) => !/extension|analytics|gtag|favicon/i.test(e));
      expect(ours, \`\${route}: \${ours.join(' | ')}\`).toEqual([]);
    });

    test('every image carries alt text', async ({ page }) => {
      await page.goto(route);
      await page.waitForLoadState('networkidle');
      const missing = await page.evaluate(() =>
        Array.from(document.querySelectorAll('img'))
          .filter((i) => !i.hasAttribute('alt'))
          .map((i) => i.getAttribute('src') ?? '(no src)'),
      );
      // alt="" is correct for decoration; a MISSING alt makes a screen reader
      // read the filename aloud.
      expect(missing, \`\${route} images without alt: \${missing.join(', ')}\`).toEqual([]);
    });
  });
}
`;
}

/* ── Permission matrix, from the database ───────────────────────────────── */

const PERM_SPEC = `${HEADER}
import { test, expect } from '@playwright/test';

/**
 * Generated from role_capabilities at run time rather than at generate time:
 * the matrix is read from the live database inside the test, so a role or
 * resource added by a migration is covered without regenerating anything.
 *
 * This asserts the SHAPE of the matrix, not specific grants — which role may
 * publish is the adopter's policy, not ours. What is universal: deny-by-
 * default must hold, and an acting capability must not outrank the view it
 * depends on.
 */
test.describe('permission matrix invariants', () => {
  test.skip(!process.env.DATABASE_URL, 'DATABASE_URL not set — permission invariants not checked');

  test('no role acts on a resource it cannot view', async () => {
    const { Client } = await import('pg');
    const db = new Client({ connectionString: process.env.DATABASE_URL });
    await db.connect();
    try {
      const { rows } = await db.query(\`
        SELECT acting.role, acting.resource_key, acting.action
          FROM public.role_capabilities acting
         WHERE acting.action IN ('create','edit','delete','publish')
           AND acting.allowed
           AND EXISTS (SELECT 1 FROM public.role_capabilities v
                        WHERE v.role = acting.role
                          AND v.resource_key = acting.resource_key
                          AND v.action = 'view')
           AND NOT EXISTS (SELECT 1 FROM public.role_capabilities v
                            WHERE v.role = acting.role
                              AND v.resource_key = acting.resource_key
                              AND v.action = 'view'
                              AND v.allowed)
      \`);
      const offenders = rows.map((r) => \`\${r.role} may \${r.action} \${r.resource_key} but cannot view it\`);
      expect(offenders, offenders.join('; ')).toEqual([]);
    } finally {
      await db.end();
    }
  });
});
`;

/* ── Main ───────────────────────────────────────────────────────────────── */

const routes = discoverRoutes();

if (process.argv.includes('--list')) {
  console.log(`  ${routes.length} routes discovered:`);
  routes.forEach((r) => console.log(`    ${r}`));
  process.exit(0);
}

if (existsSync(OUT_DIR)) rmSync(OUT_DIR, { recursive: true });
mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, 'routes.spec.ts'), routeSpec(routes));
writeFileSync(join(OUT_DIR, 'permissions.spec.ts'), PERM_SPEC);

console.log(`  generated ${OUT_DIR}/routes.spec.ts      (${routes.length} routes x 4 checks)`);
console.log(`  generated ${OUT_DIR}/permissions.spec.ts (matrix invariants, DB-driven)`);
console.log(`  routes: ${routes.join(' ')}`);
