#!/usr/bin/env node
/**
 * migration-map.mjs — what each migration creates, and what tier it is.
 *
 * Generates docs/MIGRATIONS.md. Run it after adding a migration rather than
 * editing the doc by hand: a hand-maintained table of 76 migrations is wrong
 * within a week, and a wrong map is worse than none because people trust it.
 *
 * Reuses the classifier from sql-classify.mjs for the DDL/DML tier, so the two
 * cannot disagree.
 *
 *   node scripts/migration-map.mjs            # write docs/MIGRATIONS.md
 *   node scripts/migration-map.mjs --print    # stdout only
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const DIR = 'supabase/migrations';

/** Strip dollar-quoted bodies — a CREATE TABLE inside a DO block is not a table. */
function stripDollarQuoted(sql) {
  let out = '', i = 0;
  while (i < sql.length) {
    const open = sql.indexOf('$', i);
    if (open === -1) { out += sql.slice(i); break; }
    const tagEnd = sql.indexOf('$', open + 1);
    if (tagEnd === -1) { out += sql.slice(i); break; }
    const tag = sql.slice(open, tagEnd + 1);
    if (!/^\$[A-Za-z_]*\$$/.test(tag)) { out += sql.slice(i, open + 1); i = open + 1; continue; }
    const close = sql.indexOf(tag, tagEnd + 1);
    if (close === -1) { out += sql.slice(i); break; }
    out += sql.slice(i, open) + ' ';
    i = close + tag.length;
  }
  return out;
}

const stripComments = (s) =>
  s.replace(/\/\*[\s\S]*?\*\//g, ' ').replace(/--[^\n]*/g, ' ');

function analyse(path) {
  const raw = readFileSync(path, 'utf8');
  const body = stripComments(stripDollarQuoted(raw));

  const grab = (re) => {
    const out = new Set();
    let m;
    while ((m = re.exec(body)) !== null) out.add(m[1]);
    return [...out].sort();
  };

  return {
    tables: grab(/\bCREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(?:public|auth)\.([a-z_][a-z0-9_]*)/gi),
    views: grab(/\bCREATE\s+(?:OR\s+REPLACE\s+)?(?:MATERIALIZED\s+)?VIEW\s+(?:public\.)?([a-z_][a-z0-9_]*)/gi),
    functions: grab(/\bCREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+(?:public|auth)\.([a-z_][a-z0-9_]*)/gi),
    policies: (body.match(/\bCREATE\s+POLICY\b/gi) || []).length,
    triggers: (body.match(/\bCREATE\s+TRIGGER\b/gi) || []).length,
    // The first non-empty comment line is the migration's own statement of purpose.
    title: (raw.split('\n').find((l) => /^--\s*Migration\s/i.test(l)) ||
            raw.split('\n').find((l) => /^--\s+\S/.test(l)) || '')
           .replace(/^--\s*/, '').replace(/^Migration\s+\d+:\s*/i, '').trim(),
  };
}

/** Tier comes from the existing classifier so the two documents cannot drift. */
function tiers() {
  try {
    const out = execSync('node scripts/sql-classify.mjs --json', { encoding: 'utf8' });
    return Object.fromEntries(JSON.parse(out).map((r) => [r.file, r.tier]));
  } catch {
    return {};
  }
}

const tierOf = tiers();
const files = readdirSync(DIR).filter((f) => f.endsWith('.sql')).sort();

const rows = files.map((f) => ({ file: f, tier: tierOf[f] ?? '?', ...analyse(join(DIR, f)) }));

const allTables = [...new Set(rows.flatMap((r) => r.tables))].sort();
const allViews = [...new Set(rows.flatMap((r) => r.views))].sort();
const totals = rows.reduce((a, r) => {
  a.policies += r.policies; a.triggers += r.triggers;
  a.functions += r.functions.length;
  return a;
}, { policies: 0, triggers: 0, functions: 0 });

const TIER_NOTE = {
  ddl: 'schema only',
  required: 'rows the system cannot run without',
  defaults: 'starting values, admin-editable',
  backfill: 'idempotent transform of existing rows',
  data: '**company data — never ships**',
};

const md = `# Migrations

Generated by \`node scripts/migration-map.mjs\`. **Do not edit by hand** — a table of ${files.length}
migrations maintained manually is wrong within a week, and a wrong map is worse than none
because people trust it.

## Totals

| | |
|---|---|
| Migrations | ${files.length} |
| Tables | ${allTables.length} |
| Views | ${allViews.length} |
| Functions | ${totals.functions} |
| RLS policies | ${totals.policies} |
| Triggers | ${totals.triggers} |

## Tiers — what DDL and DML mean here

Tier comes from \`scripts/sql-classify.mjs\`, which parses rather than greps: an \`INSERT\` inside a
trigger body belongs to a \`CREATE FUNCTION\` and is **DDL**, not data.

| Tier | Meaning | Goes to |
|---|---|---|
| \`ddl\` | ${TIER_NOTE.ddl} | \`migrations/\` |
| \`required\` | ${TIER_NOTE.required} | \`seed/01_required.sql\` |
| \`defaults\` | ${TIER_NOTE.defaults} | \`seed/02_defaults.sql\` |
| \`backfill\` | ${TIER_NOTE.backfill} | stays with its migration |
| \`data\` | ${TIER_NOTE.data} | admin UI or the \`site-bootstrap\` skill |

The rule that is easy to get wrong: an \`INSERT ... SELECT\` is usually a backfill, but
\`INSERT ... SELECT ... FROM (VALUES ...)\` is a literal seed written compactly — migration 003
expands the whole permission matrix that way and reads from no table at all.

## Every migration

| # | Tier | Creates | Purpose |
|---|---|---|---|
${rows.map((r) => {
  const creates = [
    r.tables.length ? `**${r.tables.length}t** ${r.tables.slice(0, 4).join(', ')}${r.tables.length > 4 ? '…' : ''}` : '',
    r.views.length ? `${r.views.length}v` : '',
    r.functions.length ? `${r.functions.length}fn` : '',
    r.policies ? `${r.policies}pol` : '',
  ].filter(Boolean).join(' · ') || '—';
  return `| \`${r.file.replace('.sql', '')}\` | ${r.tier} | ${creates} | ${r.title.slice(0, 90)} |`;
}).join('\n')}

## Every table, and where it came from

| Table | Created in |
|---|---|
${allTables.map((t) => {
  const from = rows.filter((r) => r.tables.includes(t)).map((r) => r.file.replace('.sql', '').split('_')[0]);
  return `| \`${t}\` | ${from.join(', ')} |`;
}).join('\n')}

---

## Rules

**Append-only.** Never edit an applied migration. It already ran, so the edit changes nothing on
any existing database and puts the file out of step with every deployment that has it. The fix
is always the next number.

**RLS needs a policy in the same file.** \`ENABLE ROW LEVEL SECURITY\` without a policy denies
everything and Postgres does not warn you — every query returns zero rows, with no error.

**\`view\` is a floor.** Since migration 075, an acting capability requires the view it depends
on. Granting \`create\` without \`view\` grants nothing.

**Writes go through \`perform_action()\`.** It authorizes and audits atomically, so no write path
can produce a permission decision without also producing an audit row.

**Verify inside the migration.** End with a \`DO $verify$\` block that asserts what you claimed
and raises if it is false. Migration 075 checks its own disclosure fix at apply time.
`;

if (process.argv.includes('--print')) {
  console.log(md);
} else {
  writeFileSync('docs/MIGRATIONS.md', md);
  console.log(`  docs/MIGRATIONS.md — ${files.length} migrations, ${allTables.length} tables, ` +
              `${allViews.length} views, ${totals.policies} policies`);
}
