#!/usr/bin/env node
// port-agents.mjs — make this repo's skills and bundled MCP servers usable by
// Claude Code, Codex, OpenCode and Antigravity. Source of truth:
//   skills : .claude/skills/<name>/SKILL.md   (Agent Skills standard: name + description)
//   MCP    : agents/mcp.json                  (profiles, env-var NAMES only)
// Outputs (project-level, regenerated — never edit them by hand):
//   .agents/skills/<name>/   OpenCode + Antigravity     .codex/skills/<name>/  Codex
//   .mcp.json  Claude   .codex/config.toml  Codex   opencode.json (mcp key)  OpenCode
//   .agents/mcp_config.json  Antigravity
//
//   pnpm agents:port [--profile core,coolify,whatsapp] [--site-url https://…]
//   pnpm agents:port --check        exit 1 if any generated output is stale
//   --skills-only | --mcp-only      --exclude name1,name2 (skills not to port)

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const args = process.argv.slice(2);
const flag = (n, d) => (args.includes(`--${n}`) ? args[args.indexOf(`--${n}`) + 1] : d);
const has = (n) => args.includes(`--${n}`);
const CHECK = has('check');
const MARK = 'generated by scripts/port-agents.mjs from .claude/skills — edit the source, then run pnpm agents:port';

const stale = [];
function emit(rel, content) {
  const p = join(ROOT, rel);
  const now = existsSync(p) ? readFileSync(p, 'utf8') : null;
  if (now === content) return;
  if (CHECK) return stale.push(rel);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, content);
  console.log(`  wrote ${rel}`);
}

// ── skills ──────────────────────────────────────────────────────────────────
function listFiles(dir, base = dir) {
  return readdirSync(dir).flatMap((e) => {
    const p = join(dir, e);
    return statSync(p).isDirectory() ? listFiles(p, base) : [p.slice(base.length + 1)];
  });
}

function portSkills() {
  const src = join(ROOT, '.claude', 'skills');
  const exclude = new Set((flag('exclude', '') || '').split(',').filter(Boolean));
  const skills = readdirSync(src).filter((n) => existsSync(join(src, n, 'SKILL.md')) && !exclude.has(n));
  for (const target of ['.agents/skills', '.codex/skills']) {
    for (const name of skills) {
      for (const f of listFiles(join(src, name))) {
        let body = readFileSync(join(src, name, f), 'utf8');
        if (f === 'SKILL.md') {
          // Keep only standard frontmatter keys; add a provenance marker after it.
          body = body.replace(/^---\n([\s\S]*?)\n---\n/, (_, fm) => {
            const keep = fm.split('\n').filter((l) => /^(name|description|license|metadata):|^\s/.test(l)).join('\n');
            return `---\n${keep}\n---\n<!-- ${MARK} -->\n`;
          });
        }
        emit(join(target, name, f), body);
      }
    }
    // Remove ported skills whose source is gone (only ones we generated).
    const dir = join(ROOT, target);
    if (existsSync(dir)) {
      for (const n of readdirSync(dir)) {
        const s = join(dir, n, 'SKILL.md');
        if (!skills.includes(n) && existsSync(s) && readFileSync(s, 'utf8').includes(MARK)) {
          if (CHECK) stale.push(join(target, n));
          else {
            rmSync(join(dir, n), { recursive: true });
            console.log(`  removed ${target}/${n} (source deleted)`);
          }
        }
      }
    }
  }
  return skills.length;
}

// ── MCP bundle ──────────────────────────────────────────────────────────────
function siteUrl() {
  if (flag('site-url')) return flag('site-url').replace(/\/$/, '');
  for (const f of ['src/config/site.ts', 'config/site.ts', 'lib/config/site.ts']) {
    if (!existsSync(join(ROOT, f))) continue;
    const m = readFileSync(join(ROOT, f), 'utf8').match(/url:\s*["']([^"']+)["']/);
    if (m) return m[1].replace(/\/$/, '');
  }
  return (process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000').replace(/\/$/, '');
}

function portMcp() {
  const bundle = JSON.parse(readFileSync(join(ROOT, 'agents/mcp.json'), 'utf8'));
  const profiles = (flag('profile') || bundle.default_profiles.join(',')).split(',').filter(Boolean);
  const names = [...new Set(profiles.flatMap((p) => bundle.profiles[p] ?? (() => { throw new Error(`unknown profile ${p}`); })()))];
  const url = siteUrl();
  const servers = names.map((n) => [n, { ...bundle.servers[n], url: bundle.servers[n].url?.replace('${SITE_URL}', url) }]);
  // URLs may still carry ${VAR}s (e.g. Postiz puts its key in the path). Claude expands
  // them itself and OpenCode takes {env:VAR}; Codex and Antigravity expand neither, so
  // those servers run through `sh -c` + mcp-remote, which resolves them at launch.
  const hasEnvUrl = (s) => /\$\{[A-Z0-9_]+\}/.test(s.url || '');
  const bridgeVars = (s) => [...new Set([...(s.url.match(/\$\{([A-Z0-9_]+)\}/g) || []).map((m) => m.slice(2, -1)), ...(s.bearer_env ? [s.bearer_env] : []), ...Object.values(s.headers_env || {})])];
  const shBridge = (s) => {
    const shUrl = s.url.replace(/\$\{([A-Z0-9_]+)\}/g, '$$$1');
    const h = [];
    if (s.bearer_env) h.push(`--header "Authorization:Bearer $${s.bearer_env}"`);
    for (const [k, e] of Object.entries(s.headers_env || {})) h.push(`--header "${k}:$${e}"`);
    return { command: 'sh', args: ['-c', `exec npx -y mcp-remote "${shUrl}" ${h.join(' ')}`.trim()] };
  };

  // Claude Code (.mcp.json): expands ${VAR} at load time.
  const claude = { mcpServers: {} };
  for (const [n, s] of servers) {
    if (s.transport === 'stdio') {
      claude.mcpServers[n] = { command: s.command, args: s.args, env: Object.fromEntries((s.env_passthrough || []).map((k) => [k, `\${${k}}`])) };
    } else {
      const headers = {};
      if (s.bearer_env) headers.Authorization = `Bearer \${${s.bearer_env}}`;
      for (const [h, e] of Object.entries(s.headers_env || {})) headers[h] = `\${${e}}`;
      claude.mcpServers[n] = { type: 'http', url: s.url, ...(Object.keys(headers).length ? { headers } : {}) };
    }
  }
  emit('.mcp.json', JSON.stringify(claude, null, 2) + '\n');

  // Codex (.codex/config.toml, project-scoped; trusted projects). OAuth: `codex mcp login <name>`.
  const q = JSON.stringify;
  const toml = [`# ${MARK.replace('.claude/skills', 'agents/mcp.json')}`, ''];
  for (const [n, s] of servers) {
    toml.push(`[mcp_servers.${n}]`);
    if (s.transport === 'stdio') {
      toml.push(`command = ${q(s.command)}`, `args = [${s.args.map(q).join(', ')}]`);
      if (s.env_passthrough?.length) toml.push(`env_vars = [${s.env_passthrough.map(q).join(', ')}]`);
    } else if (hasEnvUrl(s)) {
      const b = shBridge(s);
      toml.push(`command = ${q(b.command)}`, `args = [${b.args.map(q).join(', ')}]`);
      toml.push(`env_vars = [${bridgeVars(s).map(q).join(', ')}]`);
    } else {
      toml.push(`url = ${q(s.url)}`);
      if (s.bearer_env) toml.push(`bearer_token_env_var = ${q(s.bearer_env)}`);
      const he = Object.entries(s.headers_env || {});
      if (he.length) toml.push(`env_http_headers = { ${he.map(([h, e]) => `${q(h)} = ${q(e)}`).join(', ')} }`);
    }
    toml.push('');
  }
  emit('.codex/config.toml', toml.join('\n'));

  // OpenCode (opencode.json): keep any other keys, replace only `mcp`.
  const ocPath = join(ROOT, 'opencode.json');
  const oc = existsSync(ocPath) ? JSON.parse(readFileSync(ocPath, 'utf8')) : { $schema: 'https://opencode.ai/config.json' };
  oc.mcp = {};
  for (const [n, s] of servers) {
    if (s.transport === 'stdio') {
      oc.mcp[n] = { type: 'local', command: [s.command, ...s.args], environment: Object.fromEntries((s.env_passthrough || []).map((k) => [k, `{env:${k}}`])), enabled: true };
    } else {
      const headers = {};
      if (s.bearer_env) headers.Authorization = `Bearer {env:${s.bearer_env}}`;
      for (const [h, e] of Object.entries(s.headers_env || {})) headers[h] = `{env:${e}}`;
      oc.mcp[n] = { type: 'remote', url: s.url.replace(/\$\{([A-Z0-9_]+)\}/g, '{env:$1}'), ...(Object.keys(headers).length ? { headers } : {}), enabled: true };
    }
  }
  emit('opencode.json', JSON.stringify(oc, null, 2) + '\n');

  // Antigravity (.agents/mcp_config.json): remote servers use serverUrl. Env expansion in
  // headers is not documented, so bearer servers go through mcp-remote, which reads the token
  // from the agent's environment instead of a value written here.
  const agy = { mcpServers: {} };
  for (const [n, s] of servers) {
    if (s.transport === 'stdio') {
      agy.mcpServers[n] = { command: s.command, args: s.args };
    } else if (hasEnvUrl(s) || s.bearer_env || s.headers_env) {
      agy.mcpServers[n] = shBridge(s);
    } else {
      agy.mcpServers[n] = { serverUrl: s.url };
    }
  }
  emit('.agents/mcp_config.json', JSON.stringify(agy, null, 2) + '\n');
  return { profiles, names, codexToml: toml.slice(2).join('\n'), agy, servers, shBridge };
}

// ── --install-user: register in each agent's USER config ─────────────────────
// Codex and Antigravity do not (reliably) read project-level MCP config, so the
// same servers are written to their user config. Names of env vars only; tokens
// are read from the environment the agent runs in.
import { execFileSync } from 'node:child_process';
import { homedir } from 'node:os';
function installUser(mcp) {
  const repo = ROOT.split('/').pop();
  const begin = `# >>> agents:port ${repo} (generated — re-run pnpm agents:port --install-user)`;
  const end = `# <<< agents:port ${repo}`;
  const cfg = join(homedir(), '.codex', 'config.toml');
  let cur = existsSync(cfg) ? readFileSync(cfg, 'utf8') : '';
  const re = new RegExp(`\\n?${begin.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}[\\s\\S]*?${end.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\n?`);
  cur = cur.replace(re, '\n');
  // A server name already defined by hand elsewhere wins; skip it rather than duplicate the table.
  const taken = new Set([...cur.matchAll(/^\[mcp_servers\.([^\].]+)\]/gm)].map((m) => m[1]));
  // OAuth servers Codex reports as "Not logged in" fail on every start; write them switched off
  // until `codex mcp login <name>` (re-run --install-user afterwards to switch them on).
  let notLoggedIn = new Set();
  try {
    const out = execFileSync('codex', ['mcp', 'list'], { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] });
    notLoggedIn = new Set(out.split('\n').filter((l) => /Not logged in\s*$/.test(l)).map((l) => l.trim().split(/\s+/)[0]));
  } catch { /* codex missing: leave as is */ }
  const oauth = new Set(mcp.servers.filter(([, sv]) => sv.auth === 'oauth').map(([n]) => n));
  const blocks = mcp.codexToml.split(/\n(?=\[mcp_servers\.)/)
    .filter((b) => !taken.has(/\[mcp_servers\.([^\]]+)\]/.exec(b)?.[1]))
    .map((b) => {
      const n = /\[mcp_servers\.([^\]]+)\]/.exec(b)?.[1];
      return n && oauth.has(n) && notLoggedIn.has(n)
        ? b.replace(/^(\[mcp_servers\.[^\]]+\])/, `$1\n# not logged in: run \`codex mcp login ${n}\`, then pnpm agents:port --install-user\nenabled = false`)
        : b;
    });
  const off = blocks.filter((b) => /\nenabled = false/.test(b)).length;
  writeFileSync(cfg, `${cur.trimEnd()}\n\n${begin}\n${blocks.join('\n').trim()}\n${end}\n`);
  console.log(`  codex: ${blocks.length} servers in ${cfg}${off ? ` (${off} OAuth server(s) off until \`codex mcp login\`)` : ''}${taken.size ? ` (kept your own: ${[...taken].filter((t) => mcp.names.includes(t)).join(', ') || 'none clashing'})` : ''}`);
  let agyOk = 0;
  for (const [n, s] of Object.entries(mcp.agy.mcpServers)) {
    const argv = s.serverUrl ? ['mcp', 'add', n, s.serverUrl] : ['mcp', 'add', n, '--', s.command, ...s.args];
    try { execFileSync('agy', argv, { stdio: 'ignore' }); agyOk++; } catch { console.log(`  agy: could not add ${n} (is agy installed and on PATH?)`); }
  }
  if (agyOk) console.log(`  antigravity: ${agyOk} servers added (agy mcp list)`);
}

// ── run ─────────────────────────────────────────────────────────────────────
console.log(CHECK ? 'Checking generated agent files…' : 'Porting agent skills + MCP bundle…');
const nSkills = has('mcp-only') ? 0 : portSkills();
const mcp = has('skills-only') ? null : portMcp();
if (mcp && has('install-user') && !CHECK) installUser(mcp);
if (CHECK) {
  if (stale.length) {
    console.error(`stale (run pnpm agents:port):\n  ${stale.join('\n  ')}`);
    process.exit(1);
  }
  console.log('all generated agent files are current');
} else {
  if (nSkills) console.log(`skills: ${nSkills} -> .agents/skills (OpenCode, Antigravity), .codex/skills (Codex); Claude reads .claude/skills`);
  if (mcp) {
    console.log(`MCP profiles ${mcp.profiles.join(', ')}: ${mcp.names.join(', ')}`);
    console.log('OAuth servers prompt a browser login on first use (Codex: codex mcp login <name>). Bearer tokens come from your shell env.');
  }
}
